### ISSUE TITLE
I see "path.mutate" in the commits

### ISSUE THREAD

**Issue by paul-hammant** [kigster/bashmatic#44]
Is that a think the user may want to use?  I can't see it in the docs/README

I want to manage my PATH using solid technologies. Pseudo code:

PATH=path.mutate($PATH, "replace-term JavaVirtualMachines/jdk with JavaVirtualMachines/jdk-15.0.1.jdk")

I don't want to use `asdf`, `sdkman` or others. I just want something I main in a shell script I can `source`. And though I hand-maintain those, I want them to be elegant.

**Comment by kigster** [comment]
I am not what the issue is here.

You can accomplish what you want with the functions provided with the `lib/path.sh` module, [documentation of which is available here](https://github.com/kigster/bashmatic/blob/master/doc/USAGE.md#file-libpathsh).

Basically,

```bash

path.mutate.delete /opt/local/libexe /opt/local/bin
path.mutate.prepend /usr/local/bin
path.mutate.prepend ${HOME}/bin
````
